name: Push README to Docker Hub
'on':
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/auto-push-readme.yml
jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_TOKEN }}
        with:
          destination_container_repo: keanubdh/pihole-unbound
          provider: dockerhub
          short_description: 'A fork of Pihole + Unbound by [aleksanderbl29](https://github.com/aleksanderbl29) modified with DoT.'
          readme_file: 'README.md'
